version: '3.8'

#  /**
#  * M1 Silicon - use Colima. 'colima start --arch amd'
#  * See <a href="https://github.com/microsoft/mssql-docker/issues/668">https://github.com/microsoft/mssql-docker/issues/668</a>
#  * Configure Testcontainers to use colima:
#  * <a href="https://www.rockyourcode.com/testcontainers-with-colima/">https://www.rockyourcode.com/testcontainers-with-colima/</a>
#  * Or add env vars:
#  * TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE=/var/run/docker.sock
#  * DOCKER_HOST=unix://${HOME}/.colima/docker.sock
#
# colima start --cpu 2 --memory 4 --arch amd
# docker-compose --compatibility up -d
#  */
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.22
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    environment:
      - xpack.ml.enabled=false
      - bootstrap.memory_lock=false
      - discovery.type=single-node
      - ELASTIC_PASSWORD=elastic-12345678
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m -XX:UseSSE=2"
    ports:
      - 9200:9200
    deploy:
      resources:
        limits:
          memory: 800M

  canonical-db:
    image: mcr.microsoft.com/mssql/server:2017-CU24-ubuntu-16.04
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=CANON-05844853-b0f0-4be9-b7b4-d793c2bcd600
    ports:
      - "1433:1433"
    deploy:
      resources:
        limits:
          memory: 1200M

  master-db:
    image: mcr.microsoft.com/mssql/server:2017-CU24-ubuntu-16.04
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MASTER-05844853-b0f0-4be9-b7b4-d793c2bcd600
    ports:
      - "1434:1433"
    deploy:
      resources:
        limits:
          memory: 1200M
